name: Tests
on:
  pull_request:
  push:
    branches:
      - master
      - release/**

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/main'"

  install-tparse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.18
      - name: Display Go Version
        run: go version
      - name: Install tparse
        run: |
          export GO111MODULE="on" && go install github.com/mfridman/tparse@latest
      - uses: actions/cache@v2.1.7
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-tparse-binary

  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.18
      - uses: actions/checkout@v2.4.0
      - uses: technote-space/get-diff-action@v5
        with:
          PATTERNS: |
            **/**.sol
            **/**.go
            go.mod
            go.sum
      - name: Test unit
        run: |
          make test-unit
